server.port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIE
          uri: lb://MOVIE
          predicates:
            - Path=/movie/**
        - id: BOOKING
          uri: lb://BOOKING
          predicates:
            - Path=/booking/**  
        - id: CITY
          uri: lb://CITY
          predicates:
            - Path=/city/**
        - id: SCREEN
          uri: lb://SCREEN
          predicates:
            - Path=/screen/**
        - id: SEAT
          uri: lb://SEAT
          predicates:
            - Path=/seat/**
        - id: THEATER
          uri: lb://THEATER
          predicates:
            - Path=/theater/**
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/user/**            
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    